# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simply export full statistics to Rcpp::List
#' @param model
NULL

#' Calibrate credible sets per level
#' @param model
#' @param coverage
#'
NULL

#' Estimate a multi-trait Sum of Single Effect regression model
#'
#' @param x          design matrix
#' @param y          output matrix
#' @param levels     number of "single" effects
#' @param max_iter   maximum iterations
#' @param min_iter   minimum iterations
#' @param tol        tolerance
#' @param prior_var  prior variance
#'
#' @return a list of mtSusie results
#'
#' \item{alpha}{Posterior probability of variant across k traits; `alpha[j,l]`}
#' \item{resid.var}{Residual variance; `alpha[l,k]`}
#'
fit_mt_susie <- function(x, y, levels = 15L, max_iter = 100L, min_iter = 5L, coverage = .9, tol = 1e-8, prior_var = 100.0, lodds_cutoff = 0) {
    .Call('_mtSusie_fit_mt_susie', PACKAGE = 'mtSusie', x, y, levels, max_iter, min_iter, coverage, tol, prior_var, lodds_cutoff)
}

