# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate mtSusie regression model with an interaction matrix
#'
#' @param x          design matrix
#' @param y          output matrix
#' @param w          interaction matrix
#' @param levels     number of "single" effects
#' @param max_iter   maximum iterations
#' @param min_iter   minimum iterations
#' @param tol        tolerance
#' @param prior_var  prior variance
#' @param min_pip_cutoff minimum PIP cutoff in building credible sets
#' @param full_stat keep full statistics
#' @param stdize_lbf trait-wise standardize LBF
#' @param local_residual locally calculate residuals
#'
#'
#' @return a list of mtSusie results
#' \item{alpha}{Posterior probability of variant across `p x level`}
#' \item{resid.var}{residual variance `level x traits`}
#' \item{prior.var}{prior variance `1 x traits`}
#' \item{log.odds}{log-odds ratio `level x traits`}
#' \item{mu}{a list of `p x m` mean parameters}
#' \item{var}{a list of `p x m` variance parameters}
#' \item{lbf}{a list of `p x m` log-Bayes Factors}
#' \item{z}{a list of `p x m` z-scores}
#' \item{n}{number of samples}
#' \item{m}{number of traits/outputs}
#' \item{p}{number of variants}
#' \item{L}{number of layers/levels}
#'
#' \item{cs}{credible sets (use `data.table::setDT` to assemble)}
#'
#' In the `cs`, we have
#' \item{variants}{variant indexes `[1 .. p]`}
#' \item{traits}{trait indexes `[1 .. m]`}
#' \item{levels}{levels `[1 .. L]`}
#' \item{alpha}{shared PIP}
#' \item{mean}{univariate mean}
#' \item{var}{univariate var}
#' \item{z}{univariate z-score}
#' \item{lfsr}{local false sign rate}
#' \item{lodds}{log-odds ratio}
#' \item{interaction}{interacting column index}
#'
fit_mt_interaction_susie <- function(x, y, w, levels_per_inter = 3L, max_iter = 100L, min_iter = 1L, coverage = .9, tol = 1e-4, prior_var = 0.1, min_pip_cutoff = NULL, full_stat = TRUE, stdize_lbf = FALSE, local_residual = FALSE, add_marginal = TRUE) {
    .Call('_mtSusie_fit_mt_interaction_susie', PACKAGE = 'mtSusie', x, y, w, levels_per_inter, max_iter, min_iter, coverage, tol, prior_var, min_pip_cutoff, full_stat, stdize_lbf, local_residual, add_marginal)
}

#' Estimate a multi-trait Sum of Single Effect regression model
#'
#' @param x          design matrix
#' @param y          output matrix
#' @param levels     number of "single" effects
#' @param max_iter   maximum iterations
#' @param min_iter   minimum iterations
#' @param tol        tolerance
#' @param prior_var  prior variance
#' @param lodds_cutoff log-odds cutoff in trait selection steps
#' @param min_pip_cutoff minimum PIP cutoff in building credible sets
#' @param full_stat keep full statistics
#' @param stdize_lbf trait-wise standardize LBF
#' @param local_residual locally calculate residuals
#'
#'
#' @return a list of mtSusie results
#' \item{alpha}{Posterior probability of variant across `p x level`}
#' \item{resid.var}{residual variance `level x traits`}
#' \item{prior.var}{prior variance `1 x traits`}
#' \item{log.odds}{log-odds ratio `level x traits`}
#' \item{mu}{a list of `p x m` mean parameters}
#' \item{var}{a list of `p x m` variance parameters}
#' \item{lbf}{a list of `p x m` log-Bayes Factors}
#' \item{z}{a list of `p x m` z-scores}
#' \item{n}{number of samples}
#' \item{m}{number of traits/outputs}
#' \item{p}{number of variants}
#' \item{L}{number of layers/levels}
#'
#' \item{cs}{credible sets (use `data.table::setDT` to assemble)}
#'
#' In the `cs`, we have
#' \item{variants}{variant indexes `[1 .. p]`}
#' \item{traits}{trait indexes `[1 .. m]`}
#' \item{levels}{levels `[1 .. L]`}
#' \item{alpha}{shared PIP}
#' \item{mean}{univariate mean}
#' \item{var}{univariate var}
#' \item{z}{univariate z-score}
#' \item{lfsr}{local false sign rate}
#' \item{lodds}{log-odds ratio}
#'
fit_mt_susie <- function(x, y, levels = 15L, max_iter = 100L, min_iter = 1L, coverage = .9, tol = 1e-4, prior_var = 0.1, lodds_cutoff = 0, min_pip_cutoff = NULL, full_stat = TRUE, stdize_lbf = FALSE, local_residual = FALSE) {
    .Call('_mtSusie_fit_mt_susie', PACKAGE = 'mtSusie', x, y, levels, max_iter, min_iter, coverage, tol, prior_var, lodds_cutoff, min_pip_cutoff, full_stat, stdize_lbf, local_residual)
}

